[package]
name = "nsis-plugin"
version = "0.0.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies.windows-sys]
version = "0.42.0"
features = ["Win32_System_Memory", "Win32_Foundation", "Win32_Globalization"]
